version: '3.8'
services:
  web:
    build: .
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "80:80"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
  database:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
