version: '3'
services:
  web:
    build: .
    restart: always
    depends_on:
      database:
        condition: service_started
    ports:
      - "80:80"
  database:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
