"""loaded_at alter

Revision ID: cb955a4161a6
Revises: 49852a395b92
Create Date: 2023-10-21 20:24:36.532027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb955a4161a6'
down_revision: Union[str, None] = '49852a395b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('loaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'loaded_at')
    # ### end Alembic commands ###
